services:
  postgres:
    image: postgres:15-alpine
    container_name: mybank_postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - mybank_pgdata:/var/lib/postgresql/data
    networks:
      - private_network
  
  backend:
    build: ./Backend/MyBank
    container_name: mybank_backend
    ports:
      - 8080:8080
    environment:
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    networks:
      - private_network
      - public_network
    volumes:
      - ./Backend/MyBank/uploads:/app/uploads

  frontend:
    build: ./Frontend/MyBank
    container_name: mybank_frontend
    ports:
      - 4000:4000
    networks:
      - public_network

volumes:
  mybank_pgdata:

networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge