services:
  postgres:
    image: postgres:15-alpine
    container_name: mybank_postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - mybank_pgdata:/var/lib/postgresql/data

volumes:
  mybank_pgdata: